//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_permission
    {
        public int PermissionID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> Access { get; set; }
    
        public virtual eng_module eng_module { get; set; }
        public virtual eng_usergroup eng_usergroup { get; set; }
    }
}
