//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_sys_rm_severity
    {
        public int RMSVID { get; set; }
        public Nullable<int> Severity_Value { get; set; }
        public string Severity_Type { get; set; }
        public string Severity_Description { get; set; }
    }
}
