//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_PTW_Employee_Details
    {
        public int PTWEmployeeID { get; set; }
        public Nullable<int> PTW_Master_ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual eng_ptw_master eng_ptw_master { get; set; }
    }
}
