//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_PTW_Conspc_Detail_Stage1
    {
        public int PTW_Conspc_Stage1_ID { get; set; }
        public Nullable<int> PTW_Master_ID { get; set; }
        public Nullable<int> PTW_Stage_One_ID { get; set; }
        public Nullable<int> Is_Applicable_Applicant { get; set; }
        public Nullable<int> Is_Applicable_Assessor { get; set; }
        public string Assessor_Remarks { get; set; }
    
        public virtual eng_ptw_conspc_master eng_ptw_conspc_master { get; set; }
        public virtual eng_sys_ptw_stage1_config eng_sys_ptw_stage1_config { get; set; }
    }
}
