//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_sys_ptw_stage1_config
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_sys_ptw_stage1_config()
        {
            this.eng_PTW_Conspc_Detail_Stage1 = new HashSet<eng_PTW_Conspc_Detail_Stage1>();
            this.eng_PTW_Detail_Satge1 = new HashSet<eng_PTW_Detail_Satge1>();
        }
    
        public int PTW_Stage_One_ID { get; set; }
        public string PTW_Type { get; set; }
        public string PTW_Title { get; set; }
        public string Item { get; set; }
        public Nullable<int> Order_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_PTW_Conspc_Detail_Stage1> eng_PTW_Conspc_Detail_Stage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_PTW_Detail_Satge1> eng_PTW_Detail_Satge1 { get; set; }
    }
}
