//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_qa_defect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_qa_defect()
        {
            this.eng_qa_defect_detail = new HashSet<eng_qa_defect_detail>();
            this.eng_qa_defect_files = new HashSet<eng_qa_defect_files>();
        }
    
        public int DefectID { get; set; }
        public string DefectDisplayID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Location { get; set; }
        public string DrawingRecordNo { get; set; }
        public string InspectionArea { get; set; }
        public Nullable<int> SupplierFlag { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Remarks { get; set; }
        public string DefStatus { get; set; }
        public Nullable<int> InspectedBy { get; set; }
        public Nullable<System.DateTime> InspectedDate { get; set; }
        public Nullable<int> PM_Incharge { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string InspectionType { get; set; }
        public string Ext_AuditedBy { get; set; }
        public string Ext_Auditor_Desig { get; set; }
    
        public virtual eng_employee_profile eng_employee_profile { get; set; }
        public virtual eng_employee_profile eng_employee_profile1 { get; set; }
        public virtual eng_project_master eng_project_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_qa_defect_detail> eng_qa_defect_detail { get; set; }
        public virtual eng_supplier_master eng_supplier_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_qa_defect_files> eng_qa_defect_files { get; set; }
    }
}
