//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_ptw_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_ptw_master()
        {
            this.eng_PTW_Detail_Satge1 = new HashSet<eng_PTW_Detail_Satge1>();
            this.eng_PTW_Detail_Satge4 = new HashSet<eng_PTW_Detail_Satge4>();
            this.eng_PTW_Employee_Details = new HashSet<eng_PTW_Employee_Details>();
        }
    
        public int PTW_master_ID { get; set; }
        public string CompanyName { get; set; }
        public string ProjectTitle { get; set; }
        public string NameOfApplicant { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public string Sub_con_Name { get; set; }
        public string Loc_or_GridLineNo { get; set; }
        public Nullable<System.DateTime> Start_Date_Time { get; set; }
        public Nullable<System.DateTime> End_Date_Time { get; set; }
        public Nullable<int> No_of_workers_involved { get; set; }
        public string Stage1_Person_Name { get; set; }
        public Nullable<System.DateTime> Stage1_Date_Time { get; set; }
        public string Stage2_Person_Name { get; set; }
        public Nullable<System.DateTime> Stage2_Date_Time { get; set; }
        public string Stage3_Person_Name { get; set; }
        public Nullable<System.DateTime> Stage3_Date_Time { get; set; }
        public string Stage4_Sup_Name { get; set; }
        public Nullable<System.DateTime> Stage4_Sup_Date_Time { get; set; }
        public string Stage4_WSH_Name { get; set; }
        public Nullable<System.DateTime> Stage4_WSH_Date_Time { get; set; }
        public string Stage5_Sup_Person_Name { get; set; }
        public Nullable<System.DateTime> Stage5_Sup_Date_Time { get; set; }
        public string Stage5_Mng_Person_Name { get; set; }
        public Nullable<System.DateTime> Stage5_Mng_Date_Time { get; set; }
        public string Revoke_Desc { get; set; }
        public string Revoke_Sup_Name { get; set; }
        public string Revoke_Mng_Name { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string PTW_type { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<int> CompletedStage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_PTW_Detail_Satge1> eng_PTW_Detail_Satge1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_PTW_Detail_Satge4> eng_PTW_Detail_Satge4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_PTW_Employee_Details> eng_PTW_Employee_Details { get; set; }
    }
}
