//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_po_description
    {
        public int PDID { get; set; }
        public Nullable<int> PoID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string PODescription { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<decimal> PoPrice { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual eng_po_master eng_po_master { get; set; }
    }
}
