//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_PTW_Conspc_Detail_Stage5
    {
        public int PTW_Conspc_Stage5_ID { get; set; }
        public Nullable<int> PTW_Master_ID { get; set; }
        public Nullable<System.DateTime> Stage5_Date_Time { get; set; }
        public string O2 { get; set; }
        public string CO2 { get; set; }
        public string LEL { get; set; }
        public string H2S { get; set; }
        public string Safe_for_Entry { get; set; }
        public string Stage5_Assessor_Name { get; set; }
        public string Assessor_Comments { get; set; }
    
        public virtual eng_ptw_conspc_master eng_ptw_conspc_master { get; set; }
    }
}
