//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_client_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_client_master()
        {
            this.eng_client_contact = new HashSet<eng_client_contact>();
            this.eng_outward = new HashSet<eng_outward>();
            this.eng_pymt_receivable = new HashSet<eng_pymt_receivable>();
            this.eng_quote_master = new HashSet<eng_quote_master>();
        }
    
        public int ClientID { get; set; }
        public string ClientDisplayID { get; set; }
        public string Company_Name { get; set; }
        public Nullable<int> IndustryID { get; set; }
        public Nullable<int> FunctionalityID { get; set; }
        public string Reference { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual eng_address_master eng_address_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_client_contact> eng_client_contact { get; set; }
        public virtual eng_sys_function eng_sys_function { get; set; }
        public virtual eng_sys_industry eng_sys_industry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_outward> eng_outward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_pymt_receivable> eng_pymt_receivable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_quote_master> eng_quote_master { get; set; }
    }
}
