//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_project_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_project_master()
        {
            this.eng_claim = new HashSet<eng_claim>();
            this.eng_custom_invoice = new HashSet<eng_custom_invoice>();
            this.eng_project_report = new HashSet<eng_project_report>();
            this.eng_qa_defect = new HashSet<eng_qa_defect>();
            this.eng_quote_description = new HashSet<eng_quote_description>();
            this.eng_ra_trans_master = new HashSet<eng_ra_trans_master>();
            this.eng_safety_esh = new HashSet<eng_safety_esh>();
            this.eng_safety_insp_master = new HashSet<eng_safety_insp_master>();
            this.eng_time_entry = new HashSet<eng_time_entry>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectNo { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> QuotationID { get; set; }
        public string DoNo { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Key_Milestones { get; set; }
        public string Service_Desc { get; set; }
        public Nullable<int> Project_Status_ID { get; set; }
        public string Payment_Status { get; set; }
        public string Client_Acceptance_Status { get; set; }
        public Nullable<decimal> Project_Cost { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DoDate { get; set; }
        public Nullable<int> Is_Project_level_inv { get; set; }
        public Nullable<int> Is_Custom_level_inv { get; set; }
        public Nullable<int> isFullyPaid { get; set; }
        public Nullable<int> Is_Project_level_do { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_claim> eng_claim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_custom_invoice> eng_custom_invoice { get; set; }
        public virtual eng_quote_master eng_quote_master { get; set; }
        public virtual eng_sys_location eng_sys_location { get; set; }
        public virtual eng_sys_project_status eng_sys_project_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_project_report> eng_project_report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_qa_defect> eng_qa_defect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_quote_description> eng_quote_description { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_ra_trans_master> eng_ra_trans_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_safety_esh> eng_safety_esh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_safety_insp_master> eng_safety_insp_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_time_entry> eng_time_entry { get; set; }
    }
}
