//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_transport_master
    {
        public int TransportID { get; set; }
        public string Vehicle_Name { get; set; }
        public string Vehicle_Company { get; set; }
        public string Vehicle_Model { get; set; }
        public string Vehicle_Type { get; set; }
        public string Vehicle_Number { get; set; }
        public string COE_Regn_Number { get; set; }
        public Nullable<System.DateTime> COE_Issue_Date { get; set; }
        public Nullable<System.DateTime> COE_Expiry_Date { get; set; }
        public string RoadTax_Regn_Number { get; set; }
        public Nullable<System.DateTime> RoadTax_Iussue_Date { get; set; }
        public Nullable<System.DateTime> RoadTax_Expiry_Date { get; set; }
        public string Insurance_Policy_Number { get; set; }
        public Nullable<System.DateTime> Insurance_Issue_Date { get; set; }
        public Nullable<System.DateTime> Insurance_Expiry_Date { get; set; }
        public string Insurance_Company { get; set; }
        public Nullable<System.DateTime> Last_Insurance_Renew_Date { get; set; }
        public Nullable<System.DateTime> Vehicle_Inspection_Date { get; set; }
        public Nullable<System.DateTime> Inspection_Due_Date { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string AgreementNumber { get; set; }
    }
}
