//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_ra_trans_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_ra_trans_master()
        {
            this.eng_ra_trans_detail1 = new HashSet<eng_ra_trans_detail1>();
            this.eng_ra_trans_racm = new HashSet<eng_ra_trans_racm>();
        }
    
        public int RAID { get; set; }
        public string RARefNum { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string CompanyName { get; set; }
        public string ContractNumber { get; set; }
        public string Process { get; set; }
        public string ActivityLocation { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public Nullable<System.DateTime> LastReviewDate { get; set; }
        public Nullable<System.DateTime> NextReviewDate { get; set; }
        public string RALeader { get; set; }
        public string RAMember1 { get; set; }
        public string RAMember2 { get; set; }
        public string RAMember3 { get; set; }
        public string RAMember4 { get; set; }
        public string RAMember5 { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedDesig { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Reference_Number { get; set; }
        public string PreparedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual eng_project_master eng_project_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_ra_trans_detail1> eng_ra_trans_detail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_ra_trans_racm> eng_ra_trans_racm { get; set; }
    }
}
