//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_claim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_claim()
        {
            this.eng_claim_description = new HashSet<eng_claim_description>();
            this.eng_claim_files = new HashSet<eng_claim_files>();
            this.eng_pymt_payable = new HashSet<eng_pymt_payable>();
        }
    
        public int ClaimID { get; set; }
        public string ClaimDisplayID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ClaimAgainst { get; set; }
        public Nullable<int> Status { get; set; }
        public string SVRemarks { get; set; }
        public string ApprovalRemarks { get; set; }
        public string RejectRemarks { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<int> isFullyPaid { get; set; }
        public Nullable<decimal> TotalClaim { get; set; }
        public string PaymentSource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_claim_description> eng_claim_description { get; set; }
        public virtual eng_employee_profile eng_employee_profile { get; set; }
        public virtual eng_project_master eng_project_master { get; set; }
        public virtual eng_users eng_users { get; set; }
        public virtual eng_users eng_users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_claim_files> eng_claim_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_pymt_payable> eng_pymt_payable { get; set; }
    }
}
