//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_client_contact
    {
        public int CCID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string NamePrefix { get; set; }
        public string SPOCName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Tel { get; set; }
        public string Remarks { get; set; }
    
        public virtual eng_client_master eng_client_master { get; set; }
    }
}
