//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_custom_invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_custom_invoice()
        {
            this.eng_custom_invoice_details = new HashSet<eng_custom_invoice_details>();
        }
    
        public int InvoiceID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> QuotationID { get; set; }
        public string InvoiceNo { get; set; }
        public string DoNo { get; set; }
        public Nullable<System.DateTime> DODate { get; set; }
        public Nullable<int> isFullyPaid { get; set; }
        public Nullable<decimal> FinalInvoiceAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_custom_invoice_details> eng_custom_invoice_details { get; set; }
        public virtual eng_project_master eng_project_master { get; set; }
        public virtual eng_quote_master eng_quote_master { get; set; }
    }
}
