//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_custom_invoice_details
    {
        public int InvoiceDetailsID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string QuoteDescription { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<decimal> QuotePrice { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual eng_custom_invoice eng_custom_invoice { get; set; }
    }
}
