//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_project_report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_project_report()
        {
            this.eng_project_report_files = new HashSet<eng_project_report_files>();
        }
    
        public int ProjectReportID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<System.TimeSpan> Start_Date_Time { get; set; }
        public Nullable<System.TimeSpan> End_Date_Time { get; set; }
        public string Task_Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> TaskStatusID { get; set; }
        public string Remarks { get; set; }
        public string Resource_name { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string ProgressPercentage { get; set; }
    
        public virtual eng_project_master eng_project_master { get; set; }
        public virtual eng_sys_task_status eng_sys_task_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_project_report_files> eng_project_report_files { get; set; }
    }
}
