//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_PTW_Detail_Satge4
    {
        public int PTW_Detail_Satge4 { get; set; }
        public Nullable<int> PTW_Master_ID { get; set; }
        public string Day { get; set; }
        public Nullable<System.DateTime> DayDate { get; set; }
        public string Sup_Signature { get; set; }
        public Nullable<System.DateTime> Sup_Sig_Date { get; set; }
        public string Mng_Signature { get; set; }
        public Nullable<System.DateTime> Mng_Sig_Date { get; set; }
    
        public virtual eng_ptw_master eng_ptw_master { get; set; }
    }
}
