//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_ra_trans_racm
    {
        public int RACMID { get; set; }
        public Nullable<int> RAID { get; set; }
        public Nullable<int> RAWADetID { get; set; }
        public string RAWADetail { get; set; }
        public string HazardID { get; set; }
        public string PAHID { get; set; }
        public string REvExRCID { get; set; }
        public Nullable<int> REvRMLHID { get; set; }
        public Nullable<int> REvRMSVID { get; set; }
        public Nullable<int> REvRPN { get; set; }
        public string RCAdRCID { get; set; }
        public Nullable<int> RCRMLHID { get; set; }
        public Nullable<int> RCRMSVID { get; set; }
        public Nullable<int> RCRPN { get; set; }
        public string ImpOfficer { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Remarks { get; set; }
        public string PreparedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual eng_ra_trans_master eng_ra_trans_master { get; set; }
    }
}
