//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_mm_trmaster
    {
        public int MMTRID { get; set; }
        public string inoutadj_ref { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UoM { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<System.DateTime> Trn_Date { get; set; }
    
        public virtual eng_product_master eng_product_master { get; set; }
    }
}
