//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_supplier_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_supplier_master()
        {
            this.eng_inward = new HashSet<eng_inward>();
            this.eng_po_master = new HashSet<eng_po_master>();
            this.eng_qa_defect = new HashSet<eng_qa_defect>();
        }
    
        public int SupplierID { get; set; }
        public string SupplierDisplayID { get; set; }
        public string Company_Name { get; set; }
        public Nullable<int> IndustryID { get; set; }
        public string Spoc_Name { get; set; }
        public string Supplier_Description { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual eng_address_master eng_address_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_inward> eng_inward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_po_master> eng_po_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_qa_defect> eng_qa_defect { get; set; }
        public virtual eng_sys_industry eng_sys_industry { get; set; }
    }
}
