//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_inward
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_inward()
        {
            this.eng_mm_inwdesc = new HashSet<eng_mm_inwdesc>();
        }
    
        public int Inward_ID { get; set; }
        public string Inward_Number { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string Branch_Name { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Invoice_or_DO_Number { get; set; }
        public Nullable<System.DateTime> Invoice_or_DO_Date { get; set; }
        public Nullable<int> Receipt_Type { get; set; }
        public Nullable<System.DateTime> Received_Date { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DraftFlag { get; set; }
    
        public virtual eng_employee_profile eng_employee_profile { get; set; }
        public virtual eng_store_master eng_store_master { get; set; }
        public virtual eng_supplier_master eng_supplier_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_mm_inwdesc> eng_mm_inwdesc { get; set; }
    }
}
