//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_pymt_payable
    {
        public int PymtID { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> Tr_date { get; set; }
        public Nullable<System.DateTime> Due_date { get; set; }
        public string PoNo { get; set; }
        public Nullable<int> Tr_status { get; set; }
        public string reference { get; set; }
        public string FY { get; set; }
        public string Particulars { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string GTAX { get; set; }
        public string PreparedBy { get; set; }
        public string ApprovedBy { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ExpenseFlag { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> ClaimID { get; set; }
        public string PayableType { get; set; }
        public string ClaimNo { get; set; }
        public Nullable<int> PoID { get; set; }
    
        public virtual eng_claim eng_claim { get; set; }
        public virtual eng_employee_profile eng_employee_profile { get; set; }
        public virtual eng_po_master eng_po_master { get; set; }
        public virtual eng_sys_pymt_status eng_sys_pymt_status { get; set; }
    }
}
