//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_screens
    {
        public int SCREEN_ID { get; set; }
        public int MODULEID { get; set; }
        public string SCREEN_NAME { get; set; }
        public string SCREEN_CLASS_NAME { get; set; }
        public string SCREEN_URL { get; set; }
        public int ORDER_BY { get; set; }
    
        public virtual eng_module eng_module { get; set; }
    }
}
