//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_invoice_details
    {
        public int InvoiceDescID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Description { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual eng_invoice_master eng_invoice_master { get; set; }
    }
}
