//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_outward
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_outward()
        {
            this.eng_mm_outdesc = new HashSet<eng_mm_outdesc>();
        }
    
        public int Outward_ID { get; set; }
        public string Outward_Number { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string Branch_Name { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string DO_Number { get; set; }
        public Nullable<System.DateTime> DO_Date { get; set; }
        public Nullable<int> Outward_Type { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public string Vehicle_Number { get; set; }
        public string Delivery_Mode { get; set; }
        public string Project_Location { get; set; }
        public Nullable<int> DeliveredBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DraftFlag { get; set; }
    
        public virtual eng_client_master eng_client_master { get; set; }
        public virtual eng_employee_profile eng_employee_profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_mm_outdesc> eng_mm_outdesc { get; set; }
        public virtual eng_store_master eng_store_master { get; set; }
    }
}
