//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_qa_defect_cpa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_qa_defect_cpa()
        {
            this.eng_qa_defect_cpa_files = new HashSet<eng_qa_defect_cpa_files>();
        }
    
        public int DPCID { get; set; }
        public Nullable<int> DefectDetailID { get; set; }
        public Nullable<int> PAflag { get; set; }
        public Nullable<int> CAflag { get; set; }
        public Nullable<int> rfp_ncps { get; set; }
        public Nullable<int> rfp_mgmtreview { get; set; }
        public Nullable<int> rfp_cc { get; set; }
        public Nullable<int> rfp_ea { get; set; }
        public Nullable<int> rfp_other { get; set; }
        public string rfp_other_remarks { get; set; }
        public Nullable<int> ipt_envmt { get; set; }
        public Nullable<int> ipt_safety { get; set; }
        public Nullable<int> ipt_health { get; set; }
        public Nullable<int> ipt_insandops { get; set; }
        public Nullable<int> ipt_suggestion { get; set; }
        public string ActionTaken { get; set; }
        public string ActionBy { get; set; }
        public Nullable<System.DateTime> DoI { get; set; }
        public string FollowupAction { get; set; }
        public string Remarks { get; set; }
        public string ReviewedBy { get; set; }
        public string TrackStatus { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual eng_qa_defect_detail eng_qa_defect_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_qa_defect_cpa_files> eng_qa_defect_cpa_files { get; set; }
    }
}
