//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_sys_pymt_status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_sys_pymt_status()
        {
            this.eng_pymt_payable = new HashSet<eng_pymt_payable>();
            this.eng_pymt_receivable = new HashSet<eng_pymt_receivable>();
        }
    
        public int Id { get; set; }
        public string PymtStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_pymt_payable> eng_pymt_payable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_pymt_receivable> eng_pymt_receivable { get; set; }
        public virtual eng_sys_pymt_status eng_sys_pymt_status1 { get; set; }
        public virtual eng_sys_pymt_status eng_sys_pymt_status2 { get; set; }
    }
}
