//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_company_cert
    {
        public int ID { get; set; }
        public string Company_ID { get; set; }
        public string Company_Name { get; set; }
        public string Cert_License_Name { get; set; }
        public string BoardName { get; set; }
        public string Policy_Cert_Number { get; set; }
        public Nullable<System.DateTime> Issue_Date { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Document_Name { get; set; }
        public string UploadPath { get; set; }
    }
}
