//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_qa_defect_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_qa_defect_detail()
        {
            this.eng_qa_defect_cpa = new HashSet<eng_qa_defect_cpa>();
        }
    
        public int DefectDetailID { get; set; }
        public string DefectTrackNum { get; set; }
        public Nullable<int> DefectID { get; set; }
        public string DefectTitle { get; set; }
        public string DefectImpactDetails { get; set; }
        public string DefectStatus { get; set; }
    
        public virtual eng_qa_defect eng_qa_defect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_qa_defect_cpa> eng_qa_defect_cpa { get; set; }
    }
}
