//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_safety_insp_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_safety_insp_master()
        {
            this.eng_safety_insp_detail = new HashSet<eng_safety_insp_detail>();
        }
    
        public int SAFINSID { get; set; }
        public string SafetyRefNum { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<System.DateTime> SIDate { get; set; }
        public string ProjectLocation { get; set; }
        public string InspectedBy { get; set; }
        public string Address { get; set; }
        public string Safety_Cert_Info { get; set; }
        public string Others1 { get; set; }
        public string Others2 { get; set; }
        public string Others3 { get; set; }
        public string Others4 { get; set; }
        public string Others5 { get; set; }
        public string Others6 { get; set; }
        public string Others7 { get; set; }
        public string Others8 { get; set; }
        public string Others9 { get; set; }
        public string Others10 { get; set; }
        public string RP1 { get; set; }
        public string RP2 { get; set; }
        public string RP3 { get; set; }
        public string RP4 { get; set; }
        public string RP5 { get; set; }
        public string RP6 { get; set; }
        public string RP7 { get; set; }
        public string RP8 { get; set; }
        public string RP9 { get; set; }
        public string RP10 { get; set; }
        public Nullable<System.DateTime> ACDate1 { get; set; }
        public Nullable<System.DateTime> ACDate2 { get; set; }
        public Nullable<System.DateTime> ACDate3 { get; set; }
        public Nullable<System.DateTime> ACDate4 { get; set; }
        public Nullable<System.DateTime> ACDate5 { get; set; }
        public Nullable<System.DateTime> ACDate6 { get; set; }
        public Nullable<System.DateTime> ACDate7 { get; set; }
        public Nullable<System.DateTime> ACDate8 { get; set; }
        public Nullable<System.DateTime> ACDate9 { get; set; }
        public Nullable<System.DateTime> ACDate10 { get; set; }
        public string Senior_Construction_Manager { get; set; }
        public string Project_Manager { get; set; }
        public string Site_Manager { get; set; }
        public string Zone_Construction_Manager { get; set; }
        public string Safety_Manager { get; set; }
        public string Safety_Officer { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual eng_project_master eng_project_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_safety_insp_detail> eng_safety_insp_detail { get; set; }
    }
}
