//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_po_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_po_master()
        {
            this.eng_po_description = new HashSet<eng_po_description>();
            this.eng_pymt_payable = new HashSet<eng_pymt_payable>();
        }
    
        public int PoID { get; set; }
        public string PoRefNum { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Attention { get; set; }
        public string Branch_code { get; set; }
        public string YourRef { get; set; }
        public string PaymentTerms { get; set; }
        public string DeliveryAddress { get; set; }
        public string GTAX { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public Nullable<int> isFullyPaid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_po_description> eng_po_description { get; set; }
        public virtual eng_supplier_master eng_supplier_master { get; set; }
        public virtual eng_sys_quotestatus eng_sys_quotestatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_pymt_payable> eng_pymt_payable { get; set; }
    }
}
