//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_invoice_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_invoice_master()
        {
            this.eng_invoice_details = new HashSet<eng_invoice_details>();
        }
    
        public int InvoiceID { get; set; }
        public string InvoiceNum { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string DoNo { get; set; }
        public Nullable<System.DateTime> DoDate { get; set; }
        public string AttentionTo { get; set; }
        public Nullable<int> isFullyPaid { get; set; }
        public string GST { get; set; }
        public Nullable<decimal> TotalInvoiceAmount { get; set; }
        public string InvoiceType { get; set; }
        public string InvCategory { get; set; }
        public string InvTermandCond { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ClientOthers { get; set; }
        public string ServicesFor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_invoice_details> eng_invoice_details { get; set; }
        public virtual eng_quote_master eng_quote_master { get; set; }
    }
}
