//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_quote_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_quote_master()
        {
            this.eng_custom_invoice = new HashSet<eng_custom_invoice>();
            this.eng_invoice_master = new HashSet<eng_invoice_master>();
            this.eng_project_master = new HashSet<eng_project_master>();
            this.eng_quote_description = new HashSet<eng_quote_description>();
        }
    
        public int QuoteID { get; set; }
        public string QuoteRefNum { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> Attention_CCID { get; set; }
        public string Branch_code { get; set; }
        public string QuoteCategory { get; set; }
        public string ValidTill { get; set; }
        public string YourRef { get; set; }
        public string PaymentTerms { get; set; }
        public string TermsAndCond { get; set; }
        public string GTAX { get; set; }
        public string Currency { get; set; }
        public Nullable<int> QuoteStatusID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> IsAutoApproved { get; set; }
        public Nullable<int> IsProjectCreated { get; set; }
        public string InvoiceNo { get; set; }
        public string DoNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DODate { get; set; }
        public string QuoteTitle { get; set; }
        public Nullable<int> RvFlag { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<int> Is_invoice_released { get; set; }
        public Nullable<int> Is_Quote_level_inv { get; set; }
        public Nullable<int> Is_Project_level_inv { get; set; }
        public Nullable<int> Is_Custom_level_inv { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> isFullyPaid { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public Nullable<int> Is_do_released { get; set; }
        public Nullable<int> Is_Quote_level_do { get; set; }
        public Nullable<int> InvoiceFlag { get; set; }
    
        public virtual eng_client_master eng_client_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_custom_invoice> eng_custom_invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_invoice_master> eng_invoice_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_project_master> eng_project_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_quote_description> eng_quote_description { get; set; }
        public virtual eng_sys_quotestatus eng_sys_quotestatus { get; set; }
    }
}
