//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_ptw_conspc_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eng_ptw_conspc_master()
        {
            this.eng_PTW_Conspc_Detail_Stage1 = new HashSet<eng_PTW_Conspc_Detail_Stage1>();
            this.eng_PTW_Conspc_Detail_Stage5 = new HashSet<eng_PTW_Conspc_Detail_Stage5>();
            this.eng_PTW_Conspc_Employee_Details = new HashSet<eng_PTW_Conspc_Employee_Details>();
        }
    
        public int PTW_master_ID { get; set; }
        public string ContractorName { get; set; }
        public string Work_Description { get; set; }
        public string Applicant_Name { get; set; }
        public string Applicant_Desig { get; set; }
        public Nullable<System.DateTime> Applicant_Date_Time { get; set; }
        public string LocationOfWork { get; set; }
        public Nullable<System.DateTime> Start_Date_Time { get; set; }
        public Nullable<System.DateTime> End_Date_Time { get; set; }
        public Nullable<int> No_of_workers_involved { get; set; }
        public string Stage1_Watchman_Name { get; set; }
        public string Stage1_Watchman_ID { get; set; }
        public string Stage1_Watchman_Company { get; set; }
        public string Stage2_O2 { get; set; }
        public string Stage2_CO2 { get; set; }
        public string Stage2_LEL { get; set; }
        public string Stage2_H2S { get; set; }
        public string Safe_for_Entry { get; set; }
        public string Stage2_Assessor_Name { get; set; }
        public string Stage2_Assessor_Desig { get; set; }
        public Nullable<System.DateTime> Stage2_Assessor_Date_Time { get; set; }
        public string Stage2_Comments { get; set; }
        public string Stage3_WSH_Name { get; set; }
        public string Stage3_WSH_Desig { get; set; }
        public Nullable<System.DateTime> Stage3_WSH_Date_Time { get; set; }
        public string Stage3_Comments { get; set; }
        public string Stage4_Mng_Name { get; set; }
        public string Stage4_Mng_Desig { get; set; }
        public Nullable<System.DateTime> Stage4_Date_Time { get; set; }
        public string Stage4_Comments { get; set; }
        public string Stage6_Person_Name { get; set; }
        public string Stage6_Person_Desig { get; set; }
        public Nullable<System.DateTime> Stage6_Date_Time { get; set; }
        public string Revoke_Desc { get; set; }
        public string Revoke_WSH_Name { get; set; }
        public string Revoke_PM_Name { get; set; }
        public Nullable<System.DateTime> Revoke_Date_Time { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string PTW_type { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<int> CompletedStage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_PTW_Conspc_Detail_Stage1> eng_PTW_Conspc_Detail_Stage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_PTW_Conspc_Detail_Stage5> eng_PTW_Conspc_Detail_Stage5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eng_PTW_Conspc_Employee_Details> eng_PTW_Conspc_Employee_Details { get; set; }
    }
}
