//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class eng_company
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Auth_InvoiceName { get; set; }
        public string InvoiceTerms { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string RegNo { get; set; }
        public string GstRegNo { get; set; }
        public string LogoPath { get; set; }
        public Nullable<decimal> Normal_Work_Hours { get; set; }
        public Nullable<decimal> Weekend_Work_Hours { get; set; }
        public Nullable<decimal> Lunch_Break_Hours { get; set; }
        public Nullable<decimal> GST { get; set; }
    }
}
