//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng360Web.Models.Domain
{
    using System;
    
    public partial class TimeEntry_Result1
    {
        public Nullable<int> EmpID { get; set; }
        public string FirstName { get; set; }
        public string ReportDate { get; set; }
        public Nullable<decimal> No_of_WorkHours { get; set; }
        public Nullable<decimal> No_of_Othours { get; set; }
    }
}
